#!/usr/bin/env bash

# Remove useless pkg
pacman -Rcnsd rsh-server telnet-server

# Debloat xorg
pacman -Qqge xorg | grep -v xorg-server | grep -v xf86-video-vesa | grep -v xorg-mkfontscale | grep -v xorg-font-util | sudo pacman -Rnsd -
pacman -Rcnsd xorg-fonts-75dpi xorg-fonts-100dpi xorg-docs

# Delete old/temp files
fd -g *.old -x rm -rifv
fd -g *.tmp -x rm -rifv
fd -t e -x rm -rifv

# Remove more unneeded packages
pacman -Qtdq | pacman -Rns -
pacman -Qqd | pacman -Rsu -

# Lostfiles can beused too

# Journal
journalctl --rotate --vacuum-time=1s --vacuum-size=0B
