#!/usr/bin/env bash

# Delete junk packages
pacman -Rcnsd kate kate5-data kate-data kwrite kwrited kmail akonadi-server juk dragonplayer k3b k3b-data k3b-i18n konqueror akregator oxygen plasma-vault \
	plasma-workspace-wallpapers kdeplasma-addons plasma-thunderbolt network-manager-sstp discover plasma-thunderbolt plasma-browser-integration \
	kaccounts-integration kdeplasma-addons kwallet-pam drkonqi plasma-disks kinfocenter

# Disable kwallet
kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'

# Disable baloo
balooctl purge
balooctl disable
systemctl --user disable plasma-baloorunner
systemctl --user mask plasma-baloorunner

# Disable acessablity
systemctl --user disable app-kaccess@autostart
systemctl --user mask app-kaccess@autostart
