#!/usr/bin/env bash

# plasma-desktop junk
pacman -Rcnsd nothing

# plasma or plasma-meta junk
pacman -Rcnsd oxygen plasma-vault plasma-workspace-wallpapers kdeplasma-addons plasma-thunderbolt plasma-browser-integration \
	kdeplasma-addons kwallet-pam discover drkonqi plasma-disks kinfocenter

# kde-applications junk
pacman -Rcnsd kate kate5-data kate-data kwrite kwrited kmail akonadi-server akondi juk dragonplayer k3b k3b-data k3b-i18n konqueror \
	akregator

# ungrouped kde junk
pacman -Rcnsd kaccounts-providers kaccounts-integration network-manager-sstp

# Disable kwallet
kwriteconfig5 --file kwalletrc --group 'Wallet' --key 'Enabled' 'false'

# Disable baloo
balooctl purge
balooctl disable
systemctl --user disable plasma-baloorunner
systemctl --user mask plasma-baloorunner

# Disable accessablity
systemctl --user disable app-kaccess@autostart
systemctl --user mask app-kaccess@autostart
