#!/usr/bin/env bash
LC_ALL=C && LANG=C
set -e

# Functions
br() { for ((i = 1; i <= $(tput cols); i++)); do echo -n -; done; }

askvars() {
    br
    echo -e 'Use only small character without symbol\n'
    read -rep 'Enter new Username: ' -i 'user' USERN
    read -rep 'Enter new Hostname: ' -i 'host' HNAME
    read -rep 'Enter new Timezone: ' -i 'Asia/Kolkata' TZONE
    br
    echo -e "Username = $USERN\nHostname = $HNAME\nTimezone = $TZONE\n"
    read -rep 'Is above data correct? [Y/N]: ' DATAYN
    if [[ $DATAYN =~ ^[Yy]$ ]]; then br; else
        br
        clear
        UHOST
    fi
}

# Ask variables
askvars

# Timezone & Hwclock
ln -sf /usr/share/zoneinfo/"$TZONE" /etc/localtime
hwclock --systohc --utc #Sync system time with RTC

# Localization
sed -i 's|#en_US.UTF-8|en_US.UTF-8|g' /etc/locale.gen
locale-gen
echo -e 'LANG=en_US.UTF-8\nLANGUAGE=en_US\nLC_ALL=C' >/etc/locale.conf

# Network configuration
echo "$HNAME" >/etc/hostname
echo -e "127.0.0.1 $HNAME\n::1 $HNAME\n127.0.1.1 $HNAME.localdomain $HNAME" >/etc/hosts

# Initramfs
mkinitcpio -P

# Root Password
br && echo "Enter powerfull password for Root"
if groups | grep sudo >/dev/null; then true; else groupadd sudo; fi
until passwd || ((count++ >= 5)); do echo 'TryAgain'; done
passwd -l root # Disable root login by default

# Normal User
br && echo "Enter powerfull password for new user $USERN"
useradd -m -U -G wheel,users,games,power,optical,storage,audio,video -s /bin/bash "$USERN"
chown -R "$USERN":users /home/"$USERN"
until passwd "$USERN" || ((count++ >= 5)); do echo 'Try Again' && br; done
sed -i 's/^#\s*\(%wheel\s\+ALL=(ALL)\s\+ALL\)/\1/' /etc/sudoers

# Bootloader
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Arch

# Enable services
systemctl enable --now NetworkManager
systemctl enable --now --user pipewire pipewire-pulse wireplumber
