#!/bin/sh

exec "$JAVA_HOME/bin/java" --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-.base/java.lang=ALL-UNNAMED --add-opens=java.base/jdk.internal.org.objectweb.asm=A --add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED --add-opens/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED -javaagent:/bin/loader.jar -nor /usr/share/burpsuite-pro/burpsuite-pro.jar "$@"
