#!/usr/bin/env bash

# PKG for plasma
pacman -S --needed powerdevil dolphin gwenview plasma-firewall plasma-nm plasma-pa kscreen sddm-kcm \
		kde-gtk-config breeze-gtk kdeplasma-addons spectacle xdg-desktop-portal-kde bluedevil

# Kwallet
pacman -S --needed kwallet-pam #kwalletmanager
