#!/usr/bin/env bash

# Imp pkgs #ttf-lato ttf-fira-code inter-font
pacman -S alacritty ttf-jetbrains-mono ripgrep fd man lm_sensors thermald ufw
pacman -S reflector xorg-xinit base-devel

# Extra pkg
pacman -S x86_energy_perf_policy asp

# Disable broken UP key [Need xorg-xinit]
mkdir -pv /etc/X11/Xmodmap
echo -e 'keycode 98 = NoSymbol\nkeycode 115=' >/etc/X11/Xmodmap/Keyboard

# Pacman [Need reflector]
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
sed -i 's|#Color|Color|g' /etc/pacman.conf
sed -i 's|#VerbosePkgLists|VerbosePkgLists|g' /etc/pacman.conf
sed -i 's|#ParallelDownloads|ParallelDownloads|g' /etc/pacman.conf
reflector --latest 10 --sort rate --verbose --protocol https --save /etc/pacman.d/mirrorlist

# Journald
sed -i 's/#SystemMaxUse=/SystemMaxUse=200M/g' /etc/systemd/journald.conf
journalctl --vacuum-size=1B

# Fstrim
systemctl enable --now fstrim.timer

# Firewall [Need ufw]
systemctl enable --now ufw
ufw default deny incoming
ufw default allow outgoing
ufw enable

# Nano [Need nano]
sed -i 's|# include|include|' /etc/nanorc

# Fix touchpad + nowatchdog + no nmi_watchdog
TEMPCL='GRUB_CMDLINE_LINUX_DEFAULT="i8042.nopnp=1 nowatchdog nmi_watchdog=0 quiet loglevel=0"'
sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|$TEMPCL|g" /etc/default/grub

# Grub config
sed -i 's|GRUB_TIMEOUT=5|GRUB_TIMEOUT=1|g' /etc/default/grub
sed -i 's|#GRUB_DISABLE_SUBMENU=y|GRUB_DISABLE_SUBMENU=y|g' /etc/default/grub
sed -i 's|GRUB_DISABLE_RECOVERY=true|GRUB_DISABLE_RECOVERY=false|g' /etc/default/grub
sed -i 's|#GRUB_DISABLE_OS_PROBER=false|GRUB_DISABLE_OS_PROBER=false|g' /etc/defaut/grub

# Disable root login
passwd -l root

# SwapFile
if [ -e /swapfile ]; then echo '/swapfile already exists, skiping'; else
	dd if=/dev/zero of=/swapfile count=6144 bs=1M status=progress
	chmod -R 600 /swapfile
	echo -e '\n# Swap\n/swapfile swap swap defaults 0 0' >>/etc/fstab
	mkswap /swapfile && swapon /swapfile
fi

# Hibernation [Edit script if system is encrypted]
clear
read -rp 'Do you want to enable hibernation support? [Y/N]: ' HIBERYN
if [[ ${HIBERYN} =~ ^[Yy]$ ]]; then
	sed -i "s|HOOKS=(base.*|HOOKS=(base udev autodetect modconf block filesystems keyboard resume fsck)|g" /etc/mkinitcpio.conf
	ROOTUUID="$(findmnt -no UUID -T /swapfile)"
	SWAPOFFSET="$(filefrag -v /swapfile | awk '{ if($1=="0:"){print substr($4, 1, length($4)-2)} }')"
	TEMPCMDL="GRUB_CMDLINE_LINUX_DEFAULT=\"resume=UUID=$ROOTUUID resume_offset=$SWAPOFFSET\""
	sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|$TEMPCMDL|g" /etc/default/grub
else exit; fi

# Use lz4 compression
sed -i 's|#COMPRESSION="lz4"|COMPRESSION="lz4"|g' /etc/mkinitcpio.conf

## Blacklist junk kernel modules.
read -rp "Blacklist some Junk kernel modules (y/n) " blacklistyn
if [ "${blacklistyn}" = "y" ]; then
	echo -e '# iTCO_wdt: disables watchdog
install iTCO_wdt /bin/true
install iTCO_vendor_support /bin/true
# joydev: disables joystick [Can be enabled with `modprobe joydev` in runtime for gaming]
install joydev /bin/true
# mousedev: disables PS2 mouse support that my laptop dont have a slot for
install mousedev /bin/true
# mac_hid: Apple relatedd stuff so blacklisting this
install mac_hid /bin/true' >/etc/modprobe.d/junk.conf
fi

# Paru [Need git base-devel]
br && read -rp 'Do you want to install paru? [Y/N]: ' PARUYN
if [[ $PARUYN =~ ^[Yy]$ ]]; then
	git clone --depth=1 https://aur.archlinux.org/paru-bin.git ~/.cache/paru
	cd ~/.cache/paru
	makepkg -sic --noconfirm
fi

# Better I/O scheduler
echo '
# set scheduler for NVMe
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="none"
# set scheduler for SSD and eMMC
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
# set scheduler for rotating disks
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
' >/etc/udev/rules.d/60-ioschedulers.rules

# Enable audio powersave
echo "options snd_hda_intel power_save=1" >/etc/modprobe.d/audio_powersave.conf

# SATA powersaver
echo 'ACTION=="add", SUBSYSTEM=="scsi_host", KERNEL=="host*", ATTR{link_power_management_policy}="med_power_with_dipm"' >/etc/udev/rules.d/hd_power_save.rules

# Fancontrol [Need lm_sensors]
sensors-detect --auto
sensors
pwmconfig
systemctl enable --now fancontrol
echo -e '\n# Fix hwmon path change\ncoretemp' >>/etc/modules-load.d/modules.conf

# Thermald
systemctl enable --now thermald

# Ending
grub-mkconfig -o /boot/grub/grub.cfg
mkinitcpio -P
