#!/usr/bin/env bash

# pkgs
pacman -S --needed ttf-jetbrains-mono-nerd firefox fd ripgrep tree nano-syntax-highlighting man-db wl-clipboard spectacle

# paru
pacman -S --needed git
git clone https://aur.archlinux.org/paru-bin.git paru-bin
cd ./paru-bin || exit
makepkg -si
cd .. && rm -rfv ./paru-bin

# pacman
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
sed -i 's|#Color|Color|g' /etc/pacman.conf
sed -i 's|#VerbosePkgLists|VerbosePkgLists|g' /etc/pacman.conf
sed -i 's|#ParallelDownloads|ParallelDownloads|g' /etc/pacman.conf

# mirrors
pacman -S --needed reflector
cat <<'EOF' >/etc/xdg/reflector/reflector.conf
--save /etc/pacman.d/mirrorlist
--protocol https
--latest 10
--sort rate
--verbose
EOF
#systemctl enable --now reflector.service reflector.timer

# firewall
pacman -S --needed ufw
systemctl enable --now ufw
ufw default deny incoming
ufw default allow outgoing
ufw enable

# networkmanager
cat <<'EOF' >/etc/NetworkManager/conf.d/custom.conf
[connection]
ipv6.ip6-privacy=2
[connection-mac-randomization]
ethernet.cloned-mac-address=random
wifi.cloned-mac-address=random
EOF

# bluetooth
systemctl enable --now bluetooth

# backlight
sed -i 's|$| acpi_backlight=native|' /etc/kernel/cmdline
mkinitcpio -P

# DoH
# Configure: /etc/dns-over-https/doh-client.conf
pacman -S --needed dns-over-https
systemctl enable --now doh-client
echo -e '[global-dns-domain-*]\nservers=127.0.0.1' >>/etc/NetworkManager/conf.d/dns-servers.conf
systemctl restart NetworkManager

# Fan
paru --needed -S nbfc-linux
nbfc config --set auto
nbfc config --recommend
nbfc start
systemctl enable --now nbfc_service

# Nvidia drivers
pacman -S --needed nvidia-dkms
systemctl enable --now nvidia-resume nvidia-suspend nvidia-hibernate

# Intel drivers
pacman -S --needed intel-media-driver

# Vaapi
pacman -S --needed libva-nvidia-driver

# Vdpau
pacman -S --needed libvdpau-va-gl

# Vulkan
pacman -S --needed vulkan-icd-loader vulkan-intel vulkan-mesa-layers

# Envycontrol
paru -S --needed envycontrol
