#!/usr/bin/env bash

# Nvidia drivers
pacman -S --needed nvidia-dkms
systemctl enable --now nvidia-resume.service

# Intel drivers
pacman -S --needed intel-media-driver

# Vaapi
pacman -S --needed libva-nvidia-driver

# Vdpau
pacman -S --needed libvdpau-va-gl

# Vulkan
pacman -S --needed vulkan-icd-loader vulkan-intel vulkan-mesa-layers

# Envycontrol
paru -S --needed envycontrol
